// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXmDO1VfkTRojDz3SSlP2Wygv40qs0QDI',
    appId: '1:906931411982:web:595f4c5238a0156ebc705f',
    messagingSenderId: '906931411982',
    projectId: 'login-d0207',
    authDomain: 'login-d0207.firebaseapp.com',
    storageBucket: 'login-d0207.firebasestorage.app',
    measurementId: 'G-21R0EEF5DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD14H5mIdqpZLldwNnbt1Ak372WH2X8IfU',
    appId: '1:906931411982:android:671eac4ba9dead9abc705f',
    messagingSenderId: '906931411982',
    projectId: 'login-d0207',
    storageBucket: 'login-d0207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQagk3c7KLXQSfPE_3pUNHOfNmtaGHp1k',
    appId: '1:906931411982:ios:ff2ed5e6cee66f65bc705f',
    messagingSenderId: '906931411982',
    projectId: 'login-d0207',
    storageBucket: 'login-d0207.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQagk3c7KLXQSfPE_3pUNHOfNmtaGHp1k',
    appId: '1:906931411982:ios:ff2ed5e6cee66f65bc705f',
    messagingSenderId: '906931411982',
    projectId: 'login-d0207',
    storageBucket: 'login-d0207.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXmDO1VfkTRojDz3SSlP2Wygv40qs0QDI',
    appId: '1:906931411982:web:de50cab8f1d12a85bc705f',
    messagingSenderId: '906931411982',
    projectId: 'login-d0207',
    authDomain: 'login-d0207.firebaseapp.com',
    storageBucket: 'login-d0207.firebasestorage.app',
    measurementId: 'G-ET12VP4RCF',
  );
}
